import type {Metadata} from 'next';
import {Archivo} from 'next/font/google';
import './globals.css';

const geistArchivo = Archivo({
    variable: '--font-geist-archivo',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Jordan Shoes',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='pt-br'>
        <body
            className={`${geistArchivo.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
